"""
Application orchestrator.

Ties together: scraping → scoring → AI analysis → cover letter → notification.
This is the main workflow engine.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

import yaml

from database.db import get_db
from backend.services.job_service import (
    create_application, get_job, list_jobs, update_application_status
)
from backend.services.document_service import get_default_resume
from ai.cover_letter_generator import CoverLetterGenerator, MissingProfileDataError
from ai.matching_engine import MatchingEngine
from notifications.notifier import Notifier, NotificationEvent

logger = logging.getLogger(__name__)

_SETTINGS_PATH = Path(__file__).parent.parent / "config" / "settings.yaml"
_PROFILE_PATH = Path(__file__).parent.parent / "config" / "profile.yaml"

with open(_SETTINGS_PATH) as _f:
    _SETTINGS = yaml.safe_load(_f)
with open(_PROFILE_PATH) as _f:
    _PROFILE = yaml.safe_load(_f)


class Orchestrator:
    """
    Main workflow orchestrator.
    """

    def __init__(self):
        self.notifier = Notifier()
        self.generator = None  # Lazy init (requires API key)
        self.dry_run = _SETTINGS["safety"]["dry_run"]
        self.human_approval = _SETTINGS["safety"]["human_approval_required"]
        self.min_score = _PROFILE["application"]["min_match_score"]
        self.auto_apply_threshold = _PROFILE["application"]["auto_apply_threshold"]
        self.max_daily = _SETTINGS["safety"]["max_daily_applications"]

    # ---------------------------------------------------------------------- #
    # Full pipeline                                                            #
    # ---------------------------------------------------------------------- #

    def run_full_pipeline(self) -> dict:
        """
        1. Scrape new jobs
        2. Score and filter
        3. Generate cover letters for high-match jobs
        4. Create applications pending approval
        5. Notify user
        """
        logger.info("[Orchestrator] Starting full pipeline...")
        results = {"scraped": 0, "new_jobs": 0, "letters_generated": 0, "errors": []}

        # Step 1: Scrape
        try:
            from scrapers.scraper_manager import ScraperManager
            manager = ScraperManager()
            scrape_summary = manager.run(dry_run=self.dry_run)
            results["scraped"] = scrape_summary.get("total_found", 0)
            results["new_jobs"] = scrape_summary.get("new_jobs_saved", 0)
        except Exception as e:
            results["errors"].append(f"Scraping failed: {e}")
            logger.error(f"[Orchestrator] Scraping error: {e}")

        # Step 2: Find high-match jobs that need processing
        high_match_jobs = self._get_unprocessed_high_match_jobs()
        logger.info(f"[Orchestrator] {len(high_match_jobs)} high-match jobs to process")

        # Step 3 & 4: Generate cover letters and create applications
        for job in high_match_jobs:
            try:
                self._process_job_for_application(job)
                results["letters_generated"] += 1
            except Exception as e:
                results["errors"].append(f"Error processing job {job['id']}: {e}")
                logger.error(f"[Orchestrator] Error processing job {job['id']}: {e}")

        # Step 5: Send daily summary notification
        self._send_summary(results)
        return results

    # ---------------------------------------------------------------------- #
    # Application processing                                                  #
    # ---------------------------------------------------------------------- #

    def _process_job_for_application(self, job: dict) -> None:
        """Generate cover letter, create application, notify user."""
        job_id = job["id"]
        logger.info(f"[Orchestrator] Processing job {job_id}: {job['job_title']} @ {job['company']}")

        # Check daily limit
        if not self._within_daily_limit():
            logger.warning("[Orchestrator] Daily application limit reached.")
            return

        # Check if application already exists
        with get_db() as conn:
            existing = conn.execute(
                "SELECT id FROM applications WHERE job_id = ?", (job_id,)
            ).fetchone()
            if existing:
                logger.debug(f"[Orchestrator] Application already exists for job {job_id}")
                return

        # Generate cover letter
        cover_letter = self._generate_cover_letter(job)

        # Create application in pending state
        if not self.dry_run:
            app = create_application(job_id=job_id, notes="Auto-generated by orchestrator")
            app_id = app["id"]
            logger.info(f"[Orchestrator] Created application {app_id} for job {job_id}")

            # Save cover letter
            with get_db() as conn:
                conn.execute(
                    """
                    INSERT INTO cover_letters (job_id, content, ai_model, sources_used)
                    VALUES (?, ?, ?, ?)
                    """,
                    (
                        job_id,
                        cover_letter.get("content", ""),
                        "gpt-4o-mini",
                        json.dumps(cover_letter.get("sources_used", [])),
                    ),
                )
                conn.commit()

        # Notify user
        score = job.get("match_score", 0)
        if score >= _SETTINGS["notifications"]["high_match_threshold"]:
            self.notifier.notify_high_match(
                job_title=job["job_title"],
                company=job["company"],
                url=job.get("source_url"),
                score=score,
            )

        # If cover letter has warnings, request manual review
        if cover_letter.get("warnings") or cover_letter.get("requires_review"):
            self.notifier.notify_manual_input(
                job_title=job["job_title"],
                company=job["company"],
                url=job.get("source_url"),
                action="Review AI-generated cover letter before submitting",
            )
            if not self.dry_run:
                with get_db() as conn:
                    conn.execute(
                        """
                        INSERT INTO tasks
                            (task_type, job_id, title, description, priority)
                        VALUES ('review_letter', ?, 'Review cover letter', ?, 'high')
                        """,
                        (
                            job_id,
                            f"AI flagged issues: {'; '.join(cover_letter.get('warnings', []))}",
                        ),
                    )
                    conn.commit()

    def _generate_cover_letter(self, job: dict) -> dict:
        """Generate cover letter with anti-hallucination safeguards."""
        if not self.generator:
            try:
                self.generator = CoverLetterGenerator()
            except EnvironmentError:
                logger.warning("[Orchestrator] OpenAI key not configured — skipping cover letter")
                return {"content": "", "warnings": ["OpenAI API key not configured"], "requires_review": True}

        try:
            requirements = json.loads(job.get("requirements") or "[]")
            return self.generator.generate(
                job_title=job["job_title"],
                company=job["company"],
                job_description=job.get("description", ""),
                requirements=requirements,
            )
        except MissingProfileDataError as e:
            logger.warning(f"[Orchestrator] Missing profile data: {e}")
            self.notifier.notify_manual_input(
                job_title=job["job_title"],
                company=job["company"],
                url=job.get("source_url"),
                action=f"Profile data missing: {e}. Please update your profile.",
            )
            return {"content": "", "warnings": [str(e)], "requires_review": True}
        except Exception as e:
            logger.error(f"[Orchestrator] Cover letter generation error: {e}")
            return {"content": "", "warnings": [str(e)], "requires_review": True}

    # ---------------------------------------------------------------------- #
    # Helpers                                                                  #
    # ---------------------------------------------------------------------- #

    def _get_unprocessed_high_match_jobs(self) -> list[dict]:
        """Return high-match jobs that don't have an application yet."""
        with get_db() as conn:
            rows = conn.execute(
                """
                SELECT j.* FROM job_listings j
                LEFT JOIN applications a ON j.id = a.job_id
                WHERE j.match_score >= ? AND a.id IS NULL
                ORDER BY j.match_score DESC
                LIMIT 20
                """,
                (self.min_score,),
            ).fetchall()
            return [dict(r) for r in rows]

    def _within_daily_limit(self) -> bool:
        today = datetime.now().date().isoformat()
        with get_db() as conn:
            count = conn.execute(
                "SELECT COUNT(*) FROM applications WHERE date(created_at) = ?",
                (today,),
            ).fetchone()[0]
        return count < self.max_daily

    def _send_summary(self, results: dict) -> None:
        with get_db() as conn:
            stats = {
                "new_jobs": results.get("new_jobs", 0),
                "submitted": conn.execute(
                    "SELECT COUNT(*) FROM applications WHERE application_status = 'submitted'"
                ).fetchone()[0],
                "pending": conn.execute(
                    "SELECT COUNT(*) FROM applications WHERE application_status = 'pending'"
                ).fetchone()[0],
                "interviews": conn.execute(
                    "SELECT COUNT(*) FROM applications WHERE application_status = 'interview_invited'"
                ).fetchone()[0],
            }
        self.notifier.notify_daily_summary(stats)
