-- ============================================================
-- JOB APPLICATION PLATFORM — DATABASE SCHEMA
-- Compatible with SQLite and PostgreSQL
-- ============================================================

-- Job Listings -----------------------------------------------
CREATE TABLE IF NOT EXISTS job_listings (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    external_id     TEXT,                      -- ID from source platform
    job_title       TEXT NOT NULL,
    company         TEXT NOT NULL,
    location        TEXT,
    country         TEXT,
    remote          BOOLEAN DEFAULT FALSE,
    source          TEXT NOT NULL,             -- linkedin | indeed | direct | glassdoor
    source_url      TEXT,
    description     TEXT,
    requirements    TEXT,                      -- JSON array of extracted requirements
    salary_min      INTEGER,
    salary_max      INTEGER,
    salary_currency TEXT DEFAULT 'GBP',
    posted_date     TEXT,
    deadline        TEXT,
    match_score     REAL DEFAULT 0,            -- 0-100 computed by matching engine
    match_breakdown TEXT,                      -- JSON object with score per dimension
    priority        TEXT DEFAULT 'normal',     -- low | normal | high | priority
    esg_relevant    BOOLEAN DEFAULT FALSE,
    discovered_at   TEXT DEFAULT (datetime('now')),
    last_updated    TEXT DEFAULT (datetime('now')),
    raw_data        TEXT,                      -- Full JSON from scraper
    UNIQUE(source, external_id)
);

-- Applications -----------------------------------------------
CREATE TABLE IF NOT EXISTS applications (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id               INTEGER NOT NULL REFERENCES job_listings(id),
    application_status   TEXT DEFAULT 'pending',
    -- Statuses: pending | approved | submitted | acknowledged |
    --           interview_invited | rejected | withdrawn | on_hold
    date_applied         TEXT,
    cover_letter_id      INTEGER REFERENCES documents(id),
    resume_id            INTEGER REFERENCES documents(id),
    submission_method    TEXT,                 -- form | email | linkedin | manual
    form_url             TEXT,
    confirmation_code    TEXT,
    notes                TEXT,
    next_action_required TEXT,                 -- What needs to happen next
    next_action_due      TEXT,
    human_approved       BOOLEAN DEFAULT FALSE,
    approved_at          TEXT,
    approved_by          TEXT DEFAULT 'user',
    submitted_at         TEXT,
    automation_log       TEXT,                 -- JSON log of automation steps
    created_at           TEXT DEFAULT (datetime('now')),
    updated_at           TEXT DEFAULT (datetime('now'))
);

-- Documents --------------------------------------------------
CREATE TABLE IF NOT EXISTS documents (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    doc_type      TEXT NOT NULL,               -- resume | cover_letter | certificate | other
    file_name     TEXT NOT NULL,
    file_path     TEXT NOT NULL,
    version       TEXT,                        -- e.g. "v2", "tailored_for_CDP"
    description   TEXT,
    is_default    BOOLEAN DEFAULT FALSE,       -- Default doc for this type
    created_for   INTEGER REFERENCES job_listings(id),  -- NULL = generic
    created_at    TEXT DEFAULT (datetime('now')),
    file_size     INTEGER,
    mime_type     TEXT
);

-- Cover Letters (generated by AI) ----------------------------
CREATE TABLE IF NOT EXISTS cover_letters (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id        INTEGER REFERENCES job_listings(id),
    content       TEXT NOT NULL,
    ai_model      TEXT,
    prompt_used   TEXT,
    sources_used  TEXT,                        -- JSON: which profile sections were used
    human_edited  BOOLEAN DEFAULT FALSE,
    approved      BOOLEAN DEFAULT FALSE,
    created_at    TEXT DEFAULT (datetime('now')),
    updated_at    TEXT DEFAULT (datetime('now'))
);

-- Notifications / Tasks --------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    task_type    TEXT NOT NULL,                -- manual_input | review_letter | approve_application | other
    job_id       INTEGER REFERENCES job_listings(id),
    application_id INTEGER REFERENCES applications(id),
    title        TEXT NOT NULL,
    description  TEXT,
    status       TEXT DEFAULT 'pending',       -- pending | in_progress | completed | cancelled
    priority     TEXT DEFAULT 'normal',
    due_at       TEXT,
    completed_at TEXT,
    notification_sent BOOLEAN DEFAULT FALSE,
    created_at   TEXT DEFAULT (datetime('now'))
);

-- Scraping Runs ----------------------------------------------
CREATE TABLE IF NOT EXISTS scraping_runs (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    source       TEXT NOT NULL,
    started_at   TEXT DEFAULT (datetime('now')),
    finished_at  TEXT,
    status       TEXT DEFAULT 'running',       -- running | completed | failed
    jobs_found   INTEGER DEFAULT 0,
    jobs_new     INTEGER DEFAULT 0,
    error        TEXT,
    metadata     TEXT                          -- JSON with run details
);

-- Audit Log --------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    event_type TEXT NOT NULL,
    entity     TEXT,                           -- job | application | document | system
    entity_id  INTEGER,
    action     TEXT NOT NULL,
    details    TEXT,                           -- JSON details
    ip_address TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Indexes ----------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_jobs_status       ON job_listings(priority, match_score);
CREATE INDEX IF NOT EXISTS idx_jobs_company      ON job_listings(company);
CREATE INDEX IF NOT EXISTS idx_jobs_discovered   ON job_listings(discovered_at);
CREATE INDEX IF NOT EXISTS idx_apps_status       ON applications(application_status);
CREATE INDEX IF NOT EXISTS idx_apps_job          ON applications(job_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status      ON tasks(status, priority);
CREATE INDEX IF NOT EXISTS idx_audit_entity      ON audit_log(entity, entity_id);
